target/consensource-ui

src/addressing.js

- Updated as part of enabling Sabre support in the processor
- Format address file
Please include instructions on how to run/test your contribution. Tests are welcomed!
Disregard this if your contribution is less technical (little to no code).
`npm i`
`npm run build-dev`

Update Transaction Family Namespace to `consensource`

---

Dockerfile
src/entrypoint_factory.js
src/views/common/profile.js
src/views/factory/index.js
src/views/factory/requests.js
src/views/retailer/index.js
src/views/retailer/search.js
src/views/standards_body/index.js

Misc UI and Dockerfile fixes

---

src/views/common/auth.js
src/views/common/profile.js
src/views/factory/index.js

Add back Create Org btn

---

public/css/main.css
src/views/auditor/index.js
src/views/factory/index.js
src/views/standards_body/index.js

Misc css fixes

---

src/views/standards_body/index.js

Yarn formatting fix

---

public/css/main.css
src/services/auth.js
src/views/factory/index.js
src/views/standards_body/index.js

- CSS fixes for standards body table
- Text spacing issue on standards body landing page
- Increase logo size
- `./docker-helper.sh -r &` from the compose repo
- `cd database`
- `git pull`
- `cd ../ui`
- `npm run watch` 
- Sign up at http://localhost:8080/index_standards_body.html#!/ and visit http://localhost:8080/index_standards_body.html#!/standardsList - confirm that the table header is not cut off by the navbar

CSS fixes for standards body table

---

.travis.yml
README.md
package.json

The removed commands are no longer necessary, as we are not setting env specific config.
N/A

Remove unnecessary commands

---

src/views/standards_body/accreditations.js

- Set a default `valid_to` date of 1 year into the future when accrediting an auditor
- Set a default option of `Create A Standard` for the Standard ID dropdown
- Create a standards body (and the associated org)
- Create a standard
- Create an auditor (and the associated org)
- Visit http://localhost:8080/index_standards_body.html#!/certifyingBodyList and click the `Accredit` button for the auditor
1. Check that the `Valid To` date is 1 year in the future
2. Check that the `Standard ID` has a value of `Choose A Standard`
- Before changing any fields, hit the `Accredit Certifying Body` button. This should display an error …

Set default valid_to and standard ID

---

src/views/standards_body/index.js

Add icons to the standard body navbar.
```
cd ui
npm i
npm run build
cd..
./docker-helper.sh -r```
- Visit http://localhost:8080/index_standards_body.html#!/ and confirm that the icons in the navbar look appropriate.

Add icons to standard body navbar

---

public/css/main.css

Decreases the font size on the landing page relative to the user's view width.
Visit http://localhost:8080/index_standards_body.html#!/ and adjust the width of the window, verifying that the font on the landing page looks appropriate.

Adjust landing page font size

---

src/views/standards_body/index.js

Implement logic to update the state with an agent on the `Standards Body` header. This fixes a bug where a logged-in user wasn't having their name displayed in the `_greeting` call
Create a Standards Body account, hard refresh the page, verify that the greeting in the top left reads `Hi, <name>`

Fix agent greeting on Stds Body index

---

Dockerfile

Update the build command in Dockerfile to use the correct NPM script
`docker build .`

Update NPM build command

---

public/css/main.css

Fixes an issue with the width of the landing page content being too narrow on smaller device viewports.
View http://localhost:8080/index_retailer.html#!/ and verify that the text content does not overflow into a second column.

Fix layout width of landing page content

---

public/index.html
public/index_auditor.html
public/index_factory.html
public/index_retailer.html
public/index_standards_body.html

Add Google Analytics tags to the 5 HTML documents served to the user.
Format the HTML as well.
Rebuild the ui and inspect the page in the browser on each view to ensure the GA tag is there

Add Google Analytics 

---

package-lock.json

Fix for https://github.com/advisories/GHSA-7fhm-mqm4-2wp7
`npm i` and confirm no errors.

Patch minimist vulnerability

---

package-lock.json
package.json

Fixes https://github.com/target/consensource-ui/network/alert/package-lock.json/kind-of/open
N/A

Fix 'kind-of' devDepedency version

---

public/css/main.css
public/index.html

- Changes the order of the landing page buttons to **Standards Body, Auditor, Factory, Retailer**
- Adds a link to view the docs at http://consensource.io
- Adds a header link to https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css in the main index.html to get font-awesome resources
- `./docker-helper -r` from the compose repo and confirm that the button order is correct, styling looks good, and the link opens in a new tab.

Reorder landing page btns and add styles

---

README.md
package.json

Update README and remove format command
N/A

Update README and remove format command

---

package-lock.json
package.json
webpack.config.js

- Add webpack-dev-server
`npm run start:dev` will run the server and open the page in your browser.

Add webpack-dev-server

---

package-lock.json
package.json

From security alert
`npm i`
`npm run build`
`npm run start:dev`

Update webpack to get new serialize-javascript version

---

package-lock.json
package.json

From dependabot alert.
`npm i`
`npm run build`
`npm start:dev`
Check build logs
Visit in browser

Upgrade prebuild-install package to remediate bl CVE-2020-8244

---

package-lock.json
package.json

Update yargs-parser & serialize-javascript packages in response to dependabot
`npm i`
`npm run build`
`npm run start:dev`
Check console for errors
Visit personas in browser

Update yargs-parser & serialize-javascript packages in response to dependabot

---

package.json
src/global.d.ts
tsconfig.json
yarn.lock

- Update `typescript` dependency to latest version 
- Includes a new `global.d.ts` file for things like $TSFixME
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Other (dependency update)
`yarn start` and confirm no errors are emitted.

chore: bump TS version

---

.travis.yml
src/services/protobuf/__tests__/transaction.ts

- Comment out the linting/test steps in Travis while we refactor our tests
- Update Node version
- Switch `npm` commands to `yarn`
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

feat: Comment out travis lint/test

---

package.json
yarn.lock

- Updates vulnerabilities with `bl` and `node-forge` sub dependencies (https://github.com/target/consensource-ui/network/alerts)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Other (vulnerability patch)

chore: update vulnerable dependencies

---

.npmrc

The `.npmrc` is no longer needed as we are not pulling into our internal clone of the UI
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [x] Other (could be a small readme update, documentation contribution, etc.)

chore: remove unneeded .npmrc

---

package.json

Update react-scripts for dependabot alert
-   [x] Other (could be a small readme update, documentation contribution, etc.)
Include a screenshot of any visual changes.
`yarn`
`yarn start`

Update react-scripts for dependabot alert

---

yarn.lock

Update lockfile as well. Should remove dependabot warning.
Include a screenshot of any visual changes.
Please include instructions on how to run/test your contribution if necessary.

Update lockfile as well

---

yarn.lock

Fix lock file again
-   [x] Other (could be a small readme update, documentation contribution, etc.)
Include a screenshot of any visual changes.
Please include instructions on how to run/test your contribution if necessary.

Fix lock file again

---

src/protos/assertion.proto
src/protos/payload.proto
src/services/protobuf/__tests__/assertion.spec.ts
src/services/protobuf/__tests__/organization.spec.ts
src/services/protobuf/assertion.ts
src/services/protobuf/compiled/index.d.ts
src/services/protobuf/compiled/index.js

- Add assertion transfer protos + generated code
- Add assertion transfer service and interface
- Add assertion proto tests && fix org proto tests
-   [x] New feature (non-breaking change which adds functionality)
n/a
`yarn test src/services/protobuf/__tests__/assertion.spec.ts`
`yarn test src/services/protobuf/__tests__/organization.spec.ts`

Add Assertion Transfer Service

---

README.md

Add entity descriptions to README
-   [x] Other (could be a small readme update, documentation contribution, etc.)
n/a
n/a

Add entity descriptions to README

---

src/services/protobuf/organization.ts
src/view/forms/organization/CreateContact.tsx
src/view/forms/organization/CreateFactoryAddress.tsx
src/view/forms/organization/Organization.tsx
src/view/modals/TransferFactory/Header.tsx
src/view/modals/TransferFactory/TransferFactory.tsx
src/view/modals/TransferFactory/index.ts

- Misc styling for the `<TransferFactoryDialog />`
-   [x] Visual change (includes a change visible to an end user)
Follow instructions in https://github.com/target/consensource-ui/pull/80

fix: form alignment

---

src/services/api/factory.ts
src/view/tables/factory/FactoriesTable.tsx
src/view/tables/factory/__tests__/FactoriesTable.spec.tsx

Signed-off-by: JessicaLynnKim <JLynn.Kim@target.com>
use correct 'search' param key for factory requests
yarn start 
yarn test src/view/tables/factory/__tests__/FactoriesTable.spec.tsx

Fix api search param key for factory requests

---

package.json
tsconfig.json
yarn.lock

Bump `react-scripts` to fix a vulnerability with `node-notifier`

bump react-scripts

---

.eslintrc.js
yarn.lock

Updates the lockfile with the proper NPM registry.

feat: update lockfile

---

.npmrc
package.json
yarn.lock

Update `immer` to `8.0.1`
Include a screenshot of any visual changes.
Please include instructions on how to run/test your contribution if necessary.

Add resolution for vulnerable immer package
